kind: Service
apiVersion: v1
metadata:
  name: kubic-service
spec:
  type: NodePort
  selector:
    app: kubic-service
  ports:
    - protocol: TCP
      port: 80
      nodePort: 31080
      targetPort: 8080